// src/components/StoreLink.vue
<template>
	<a
		class="store-link"
		href="https://apple.co/3gLJDFa"
		target="_blank"
		rel="noreferrer"
	>
		<img :src="link" alt="store link" />
	</a>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
	name: 'StoreLink',
	props: {
		link: String,
	},
});
</script>

<style lang="scss" scoped>
.store-link {
	margin: 0 8px;
}
</style>

// src/components/home-page/StoreLink.tsx
import Image from "next/image";

import styles from "@/styles/components/home-page/StoreLink.module.scss";

function StoreLink({ image }: { image: typeof import("*.svg") }) {
  return (
    <a
      className={styles["store-link"]}
      href="https://apple.co/3gLJDFa"
      target="_blank"
      rel="noreferrer"
    >
      <Image src={image} alt="store link" />
    </a>
  );
}

export default StoreLink;
