// src/components/home-page/StoreLinks.tsx
import React from "react";

import useScheme from "@/hooks/useScheme";
import StoreLink from "./StoreLink";

import styles from "@/styles/components/home-page/StoreLinks.module.scss";

import appStoreBlack from "../../../public/assets/app-store-black.svg";
import appStoreWhite from "../../../public/assets/app-store-white.svg";

function StoreLinks() {
  const scheme = useScheme();

  const isDarkMode = scheme === "dark";

  return (
    <span className={styles["store-links"]}>
      <StoreLink image={isDarkMode ? appStoreBlack : appStoreWhite} />
    </span>
  );
}

export default StoreLinks;

// src/components/StoreLinks.vue
<template>
	<div id="store-links">
		<span v-for="source of appStoreSources" :key="source">
			<StoreLink :link="source" />
		</span>
	</div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

import StoreLink from './StoreLink.vue';

import AppStoreDarkSVG from '../assets/app-store-black.svg';
import AppStoreLightSVG from '../assets/app-store-white.svg';
import MacStoreDarkSVG from '../assets/mac-store-black.svg';
import MacStoreLightSVG from '../assets/mac-store-white.svg';

const assets = {
	dark: [AppStoreDarkSVG, MacStoreDarkSVG],
	light: [AppStoreLightSVG, MacStoreLightSVG],
};

function appStoreSources<T extends boolean>(this: {
	isDarkMode: T;
	appStoreSources: () => T extends true
		? typeof assets.dark
		: typeof assets.light;
}) {
	if (this.isDarkMode) return assets.dark;
	return assets.light;
}

export default defineComponent({
	name: 'StoreLinks',
	props: {
		isDarkMode: Boolean,
	},
	components: {
		StoreLink,
	},
	computed: {
		appStoreSources,
	},
});
</script>

<style lang="scss" scoped>
#store-links {
	margin: 16px auto;
}
</style>
